      - name: Build
        run: pyinstaller -n WeChatMsg --uac-admin --paths . --collect-all wxManager --collect-all exporter --add-data "exporter/resources;exporter/resources" --add-data "exporter/ffmpeg.exe;exporter" --add-data "wxManager/decrypt/version_list.json;wxManager/decrypt" wechat_tool.py
